<a href="https://colab.research.google.com/github/subham-28/PyTorch/blob/main/pipeline_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [546]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [547]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [548]:
df.shape

(569, 33)

In [549]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [550]:
df.head()

  diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [551]:
x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [552]:
#scaling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [553]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [554]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [555]:
#label encoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [556]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [557]:
#numpy arr to pytorch tensors
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)

y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [558]:
x_train_tensor.shape

torch.Size([455, 30])

building the model

In [559]:
class MyNN():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.rand(1,dtype=torch.float64,requires_grad=True)

  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    return torch.sigmoid(z)

  def binary_cross_entropy(self,y_pred,y_true):
    #clamp
    epsilon=1e-7
    y_pred=torch.clamp(y_pred,epsilon,1-epsilon)
    return -(y_true*torch.log(y_pred)+(1-y_true)*torch.log(1-y_pred)).mean()

In [560]:
learning_rate=0.1
epochs=100

In [561]:
# create model
model=MyNN(x_train_tensor)

for epoch in range(epochs):

  #forward pass
  y_pred=model.forward(x_train_tensor)

  #loss
  loss = model.binary_cross_entropy(y_pred,y_train_tensor)
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

  #backward pass
  loss.backward()

  #update params
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradient
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #pirnt loss
  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.3329484755577257
Epoch: 1, Loss: 3.3329484755577257
Epoch: 2, Loss: 3.198832256873321
Epoch: 2, Loss: 3.198832256873321
Epoch: 3, Loss: 3.0623585580154424
Epoch: 3, Loss: 3.0623585580154424
Epoch: 4, Loss: 2.9251217219059833
Epoch: 4, Loss: 2.9251217219059833
Epoch: 5, Loss: 2.7770305534563144
Epoch: 5, Loss: 2.7770305534563144
Epoch: 6, Loss: 2.6254227247429793
Epoch: 6, Loss: 2.6254227247429793
Epoch: 7, Loss: 2.47776784197829
Epoch: 7, Loss: 2.47776784197829
Epoch: 8, Loss: 2.333454492597357
Epoch: 8, Loss: 2.333454492597357
Epoch: 9, Loss: 2.1901265717138183
Epoch: 9, Loss: 2.1901265717138183
Epoch: 10, Loss: 2.043920764793607
Epoch: 10, Loss: 2.043920764793607
Epoch: 11, Loss: 1.8952603528983558
Epoch: 11, Loss: 1.8952603528983558
Epoch: 12, Loss: 1.7486978763648424
Epoch: 12, Loss: 1.7486978763648424
Epoch: 13, Loss: 1.6127622043579062
Epoch: 13, Loss: 1.6127622043579062
Epoch: 14, Loss: 1.4884155542512332
Epoch: 14, Loss: 1.4884155542512332
Epoch: 15, Loss: 1.3741555211881185
Epoch: 15, Loss: 1.3741555211881185
Epoch: 16, Loss: 1.2734692233758393
Epoch: 16, Loss: 1.2734692233758393
Epoch: 17, Loss: 1.1865672434696992
Epoch: 17, Loss: 1.1865672434696992
Epoch: 18, Loss: 1.113129288529237
Epoch: 18, Loss: 1.113129288529237
Epoch: 19, Loss: 1.0522418979904395
Epoch: 19, Loss: 1.0522418979904395
Epoch: 20, Loss: 1.0024600160406396
Epoch: 20, Loss: 1.0024600160406396
Epoch: 21, Loss: 0.9620256600166653
Epoch: 21, Loss: 0.9620256600166653
Epoch: 22, Loss: 0.929139640077928
Epoch: 22, Loss: 0.929139640077928
Epoch: 23, Loss: 0.9021674500725521
Epoch: 23, Loss: 0.9021674500725521
Epoch: 24, Loss: 0.879742896517925
Epoch: 24, Loss: 0.879742896517925
Epoch: 25, Loss: 0.8607914422194998
Epoch: 25, Loss: 0.8607914422194998
Epoch: 26, Loss: 0.8445060535787094
Epoch: 26, Loss: 0.8445060535787094
Epoch: 27, Loss: 0.8303001053394687
Epoch: 27, Loss: 0.8303001053394687
Epoch: 28, Loss: 0.8177541056984957
Epoch: 28, Loss: 0.8177541056984957
Epoch: 29, Loss: 0.8065673530367277
Epoch: 29, Loss: 0.8065673530367277
Epoch: 30, Loss: 0.7965199791744653
Epoch: 30, Loss: 0.7965199791744653
Epoch: 31, Loss: 0.7874460547420111
Epoch: 31, Loss: 0.7874460547420111
Epoch: 32, Loss: 0.7792158137430027
Epoch: 32, Loss: 0.7792158137430027
Epoch: 33, Loss: 0.7717243830536651
Epoch: 33, Loss: 0.7717243830536651
Epoch: 34, Loss: 0.7648847504248751
Epoch: 34, Loss: 0.7648847504248751
Epoch: 35, Loss: 0.7586233386147395
Epoch: 35, Loss: 0.7586233386147395
Epoch: 36, Loss: 0.7528771269719319
Epoch: 36, Loss: 0.7528771269719319
Epoch: 37, Loss: 0.7475916788011875
Epoch: 37, Loss: 0.7475916788011875
Epoch: 38, Loss: 0.7427197035765049
Epoch: 38, Loss: 0.7427197035765049
Epoch: 39, Loss: 0.7382199466470655
Epoch: 39, Loss: 0.7382199466470655
Epoch: 40, Loss: 0.7340562928013774
Epoch: 40, Loss: 0.7340562928013774
Epoch: 41, Loss: 0.7301970214152192
Epoch: 41, Loss: 0.7301970214152192
Epoch: 42, Loss: 0.7266141779398031
Epoch: 42, Loss: 0.7266141779398031
Epoch: 43, Loss: 0.7232830401987093
Epoch: 43, Loss: 0.7232830401987093
Epoch: 44, Loss: 0.7201816647328734
Epoch: 44, Loss: 0.7201816647328734
Epoch: 45, Loss: 0.7172905017863618
Epoch: 45, Loss: 0.7172905017863618
Epoch: 46, Loss: 0.7145920693155903
Epoch: 46, Loss: 0.7145920693155903
Epoch: 47, Loss: 0.7120706775487611
Epoch: 47, Loss: 0.7120706775487611
Epoch: 48, Loss: 0.7097121965373618
Epoch: 48, Loss: 0.7097121965373618
Epoch: 49, Loss: 0.7075038599904765
Epoch: 49, Loss: 0.7075038599904765
Epoch: 50, Loss: 0.7054340995094264
Epoch: 50, Loss: 0.7054340995094264
Epoch: 51, Loss: 0.7034924041403895
Epoch: 51, Loss: 0.7034924041403895
Epoch: 52, Loss: 0.7016692009173139
Epoch: 52, Loss: 0.7016692009173139
Epoch: 53, Loss: 0.6999557527587389
Epoch: 53, Loss: 0.6999557527587389
Epoch: 54, Loss: 0.698344070698237
Epoch: 54, Loss: 0.698344070698237
Epoch: 55, Loss: 0.6968268379642417
Epoch: 55, Loss: 0.6968268379642417
Epoch: 56, Loss: 0.6953973438818277
Epoch: 56, Loss: 0.6953973438818277
Epoch: 57, Loss: 0.6940494259514597
Epoch: 57, Loss: 0.6940494259514597
Epoch: 58, Loss: 0.6927774187751415
Epoch: 58, Loss: 0.6927774187751415
Epoch: 59, Loss: 0.6915761087572285
Epoch: 59, Loss: 0.6915761087572285
Epoch: 60, Loss: 0.6904406937140876
Epoch: 60, Loss: 0.6904406937140876
Epoch: 61, Loss: 0.6893667466920621
Epoch: 61, Loss: 0.6893667466920621
Epoch: 62, Loss: 0.6883501834243165
Epoch: 62, Loss: 0.6883501834243165
Epoch: 63, Loss: 0.6873872329606571
Epoch: 63, Loss: 0.6873872329606571
Epoch: 64, Loss: 0.686474411085943
Epoch: 64, Loss: 0.686474411085943
Epoch: 65, Loss: 0.6856084962068432
Epoch: 65, Loss: 0.6856084962068432
Epoch: 66, Loss: 0.6847865074372611
Epoch: 66, Loss: 0.6847865074372611
Epoch: 67, Loss: 0.6840056846527831
Epoch: 67, Loss: 0.6840056846527831
Epoch: 68, Loss: 0.6832634703164028
Epoch: 68, Loss: 0.6832634703164028
Epoch: 69, Loss: 0.682557492903439
Epoch: 69, Loss: 0.682557492903439
Epoch: 70, Loss: 0.6818855517744385
Epoch: 70, Loss: 0.6818855517744385
Epoch: 71, Loss: 0.6812456033620545
Epoch: 71, Loss: 0.6812456033620545
Epoch: 72, Loss: 0.6806357485522816
Epoch: 72, Loss: 0.6806357485522816
Epoch: 73, Loss: 0.6800542211526233
Epoch: 73, Loss: 0.6800542211526233
Epoch: 74, Loss: 0.6794993773502696
Epoch: 74, Loss: 0.6794993773502696
Epoch: 75, Loss: 0.6789696860725071
Epoch: 75, Loss: 0.6789696860725071
Epoch: 76, Loss: 0.678463720169664
Epoch: 76, Loss: 0.678463720169664
Epoch: 77, Loss: 0.677980148348076
Epoch: 77, Loss: 0.677980148348076
Epoch: 78, Loss: 0.6775177277870179
Epoch: 78, Loss: 0.6775177277870179
Epoch: 79, Loss: 0.6770752973793823
Epoch: 79, Loss: 0.6770752973793823
Epoch: 80, Loss: 0.6766517715411798
Epoch: 80, Loss: 0.6766517715411798
Epoch: 81, Loss: 0.6762461345397651
Epoch: 81, Loss: 0.6762461345397651
Epoch: 82, Loss: 0.6758574352950946
Epoch: 82, Loss: 0.6758574352950946
Epoch: 83, Loss: 0.6754847826123523
Epoch: 83, Loss: 0.6754847826123523
Epoch: 84, Loss: 0.675127340807964
Epoch: 84, Loss: 0.675127340807964
Epoch: 85, Loss: 0.6747843256943875
Epoch: 85, Loss: 0.6747843256943875
Epoch: 86, Loss: 0.6744550008921549
Epoch: 86, Loss: 0.6744550008921549
Epoch: 87, Loss: 0.6741386744404586
Epoch: 87, Loss: 0.6741386744404586
Epoch: 88, Loss: 0.6738346956801495
Epoch: 88, Loss: 0.6738346956801495
Epoch: 89, Loss: 0.6735424523853673
Epoch: 89, Loss: 0.6735424523853673
Epoch: 90, Loss: 0.6732613681221676
Epoch: 90, Loss: 0.6732613681221676
Epoch: 91, Loss: 0.6729908998144679
Epoch: 91, Loss: 0.6729908998144679
Epoch: 92, Loss: 0.6727305354994134
Epoch: 92, Loss: 0.6727305354994134
Epoch: 93, Loss: 0.6724797922558873
Epoch: 93, Loss: 0.6724797922558873
Epoch: 94, Loss: 0.6722382142913621
Epoch: 94, Loss: 0.6722382142913621
Epoch: 95, Loss: 0.6720053711736343
Epoch: 95, Loss: 0.6720053711736343
Epoch: 96, Loss: 0.6717808561951942
Epoch: 96, Loss: 0.6717808561951942
Epoch: 97, Loss: 0.6715642848590991
Epoch: 97, Loss: 0.6715642848590991
Epoch: 98, Loss: 0.6713552934762129
Epoch: 98, Loss: 0.6713552934762129
Epoch: 99, Loss: 0.6711535378645919
Epoch: 99, Loss: 0.6711535378645919
Epoch: 100, Loss: 0.670958692142622
Epoch: 100, Loss: 0.670958692142622

In [562]:
model.weights

tensor([[-0.1062],
        [ 0.1297],
        [ 0.1899],
        [ 0.2571],
        [-0.1779],
        [-0.4826],
        [ 0.0480],
        [ 0.1835],
        [ 0.0361],
        [ 0.1177],
        [ 0.2089],
        [-0.1593],
        [ 0.2129],
        [-0.3839],
        [-0.2450],
        [-0.2068],
        [ 0.0519],
        [ 0.0669],
        [ 0.2047],
        [ 0.2076],
        [-0.3000],
        [-0.0180],
        [-0.2539],
        [ 0.3561],
        [ 0.4236],
        [ 0.2796],
        [-0.0183],
        [-0.3165],
        [-0.1256],
        [-0.0306]], dtype=torch.float64, requires_grad=True)

In [563]:
model.bias

tensor([-0.4133], dtype=torch.float64, requires_grad=True)

In [564]:
# evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6120344996452332